[package]
name = "my_makedir"
version = "0.1.0"
authors = ["Koh Nakagawa <tsunekou1019@gmail.com>"]

[dependencies]
winapi = {version = "0.3.5", features = ["winuser", "fileapi", "processenv", "errhandlingapi"]}