[package]
name = "my_handleexe"
version = "0.1.0"
authors = ["Koh Nakagawa <tsunekou1019@gmail.com>"]

[dependencies]
winapi = {version = "0.3.5", features = ["processthreadsapi"]}

[dependencies.winternl]
optional = false
path = "winternl"